language: csharp
mono: none
dotnet: 2.1.502
solution: solution-name.sln
script:
  - dotnet restore
  - dotnet test ./example_sharp_tests/example_sharp_tests.csproj
  - dotnet build ./example_sharp/example_sharp.csproj